# Generated by Django 5.1 on 2025-01-16 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0002_qna'),
    ]

    operations = [
        migrations.CreateModel(
            name='busniess',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('longtitude', models.IntegerField()),
                ('latitude', models.TextField()),
                ('addressText', models.TextField()),
                ('runingHours', models.TextField()),
                ('busniessNumber', models.TextField()),
                ('instagramUrl', models.TextField()),
                ('youtubeUrl', models.TextField()),
                ('adminName', models.TextField()),
                ('adminEmail', models.TextField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='qna',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
