# Generated by Django 5.1 on 2025-01-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0003_busniess_alter_qna_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busniess',
            name='longtitude',
            field=models.TextField(),
        ),
    ]
