# Generated by Django 5.1 on 2025-01-28 03:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0004_alter_busniess_longtitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='soksoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topImages', models.TextField()),
                ('contentImages', models.TextField()),
                ('content', models.TextField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='sokso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('roomType', models.TextField(blank=True, null=True)),
                ('introduction', models.TextField()),
                ('mainImg', models.TextField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('soksoDetailId', models.ForeignKey(db_column='soksoDetailId', on_delete=django.db.models.deletion.CASCADE, related_name='soksodetail', to='joyfulset.soksodetail')),
            ],
        ),
    ]
