# Generated by Django 5.1 on 2025-01-28 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0005_soksodetail_sokso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sokso',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sokso',
            name='soksoDetailId',
            field=models.ForeignKey(blank=True, db_column='soksoDetailId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soksodetail', to='joyfulset.soksodetail'),
        ),
    ]
