# Generated by Django 5.1 on 2025-01-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0006_alter_sokso_introduction_alter_sokso_soksodetailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busniess',
            name='lastModifiedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='lastModifiedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='qna',
            name='lastModifiedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sokso',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sokso',
            name='lastModifiedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soksodetail',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soksodetail',
            name='lastModifiedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
