# Generated by Django 5.1 on 2025-01-28 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0007_alter_busniess_lastmodifiedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busniess',
            name='lastModifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='home',
            name='lastModifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='qna',
            name='lastModifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sokso',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sokso',
            name='lastModifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soksodetail',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soksodetail',
            name='lastModifiedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
