# Generated by Django 5.1 on 2025-01-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0008_alter_busniess_lastmodifiedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sokso',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
