# Generated by Django 5.1 on 2025-01-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0009_alter_sokso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sokso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
