# Generated by Django 5.1 on 2025-01-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0010_alter_qna_id_alter_sokso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sokso',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
