# Generated by Django 5.1 on 2025-01-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0011_alter_sokso_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sokso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
