# Generated by Django 5.1 on 2025-01-28 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0012_alter_sokso_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sokso',
            name='roomType',
        ),
    ]
