# Generated by Django 5.1 on 2025-01-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0013_remove_sokso_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sokso',
            name='reserveLink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
