# Generated by Django 5.1 on 2025-01-28 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0014_sokso_reservelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sokso',
            name='soksoDetailId',
        ),
        migrations.AddField(
            model_name='sokso',
            name='soksoDetail_Id',
            field=models.ForeignKey(blank=True, db_column='soksoDetail_Id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soksodetail', to='joyfulset.soksodetail'),
        ),
    ]
