# Generated by Django 5.1 on 2025-01-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0015_remove_sokso_soksodetailid_sokso_soksodetail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sokso',
            name='soksoDetail_Id',
            field=models.ForeignKey(db_column='soksoDetail_Id', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='joyfulset.soksodetail'),
        ),
    ]
