# Generated by Django 5.1 on 2025-01-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0017_imagearchive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagearchive',
            name='folder',
        ),
    ]
