# Generated by Django 5.1 on 2025-01-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0018_remove_imagearchive_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearchive',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
