# Generated by Django 5.1 on 2025-01-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0020_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='section',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
