# Generated by Django 5.1 on 2025-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0022_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='img',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
