# Generated by Django 5.1 on 2025-02-23 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0024_biz_busniess_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='home',
            name='img',
        ),
        migrations.RemoveField(
            model_name='home',
            name='section',
        ),
        migrations.AddField(
            model_name='home',
            name='imgSrc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
