# Generated by Django 5.1 on 2025-02-23 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0025_about_remove_home_contents_remove_home_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
