# Generated by Django 5.1 on 2025-02-26 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0026_home_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('introduction', models.TextField()),
                ('mainImgs', models.TextField()),
                ('optionAvailable', models.BooleanField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('structure', models.TextField()),
                ('introduction1', models.TextField()),
                ('introduction2', models.TextField(blank=True, null=True)),
                ('mainImgs', models.TextField()),
                ('content', models.TextField()),
                ('reserveLink', models.TextField(blank=True, null=True)),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('stay_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='joyfulset.stay')),
            ],
        ),
    ]
