# Generated by Django 5.1 on 2025-02-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0028_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='img',
            new_name='imgSrc',
        ),
        migrations.AddField(
            model_name='about',
            name='InstagramId',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='InstagramLink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
