# Generated by Django 5.1 on 2025-02-28 16:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0029_rename_img_about_imgsrc_about_instagramid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('introduction', models.TextField(max_length=50)),
                ('mainImg', models.TextField()),
                ('content', models.TextField()),
                ('contentImgs', models.TextField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
