# Generated by Django 5.1 on 2025-02-28 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0030_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='stay_id',
            field=models.ForeignKey(db_column='option_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='joyfulset.stay'),
            preserve_default=False,
        ),
    ]
