# Generated by Django 5.1 on 2025-02-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0031_option_stay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='stay_id',
            field=models.ForeignKey(db_column='stay_id', on_delete=django.db.models.deletion.CASCADE, to='joyfulset.stay'),
        ),
        migrations.AlterField(
            model_name='room',
            name='stay_id',
            field=models.ForeignKey(db_column='stay_id', on_delete=django.db.models.deletion.CASCADE, to='joyfulset.stay'),
        ),
    ]
