# Generated by Django 5.1 on 2025-03-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0032_alter_option_stay_id_alter_room_stay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='busniess',
            name='homeMiddleTitle',
            field=models.TextField(default='문화예술영성 공간'),
        ),
    ]
