# Generated by Django 5.1 on 2025-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0033_busniess_homemiddletitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
