# Generated by Django 5.1 on 2025-03-03 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0034_program_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('introduction', models.TextField()),
                ('imgSrc', models.TextField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='biz',
        ),
        migrations.DeleteModel(
            name='link',
        ),
        migrations.DeleteModel(
            name='sokso',
        ),
        migrations.DeleteModel(
            name='soksoDetail',
        ),
    ]
