# Generated by Django 5.1 on 2025-03-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0035_menu_delete_biz_delete_link_delete_sokso_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stay',
            old_name='introduction',
            new_name='introduction1',
        ),
        migrations.AddField(
            model_name='stay',
            name='introduction2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
