# Generated by Django 5.1 on 2025-03-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0037_alter_stay_introduction2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='contentImgs',
            new_name='mainImgs',
        ),
        migrations.RemoveField(
            model_name='option',
            name='mainImg',
        ),
        migrations.AddField(
            model_name='room',
            name='btnName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='layout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='reserveNumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
