# Generated by Django 5.1 on 2025-03-12 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0038_rename_contentimgs_option_mainimgs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='headerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('introduction1', models.TextField()),
                ('introduction2', models.TextField(blank=True, null=True)),
                ('imgSrc', models.TextField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='menu',
        ),
    ]
