# Generated by Django 5.1 on 2025-03-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0039_headerinfo_delete_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='layout',
            field=models.IntegerField(default=0),
        ),
    ]
