# Generated by Django 5.1 on 2025-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0041_remove_stay_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='btnName',
        ),
        migrations.AlterField(
            model_name='room',
            name='introduction1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
