# Generated by Django 5.1 on 2025-03-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyfulset', '0042_remove_room_btnname_alter_room_introduction1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerinfo',
            name='introduction1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
