# Generated by Django 5.1 on 2025-01-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='imgUrl',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
