# Generated by Django 5.1 on 2025-01-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_imgurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='program',
        ),
    ]
