"""
Django settings for joyfulback project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# STATIC_URL = "/static/"
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-76k=j4_vxnz$e)_74+*70)2q19ll77cebgv2zw&8yvi@f9l18r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','joyvil.com','127.0.0.1','localhost:3000','back.joyvil.com']

CORS_ALLOW_ALL = False  # ✅ Restrict access to allowed origins only

# ✅ Allow only specific frontend domains to access Django backend
CORS_ALLOWED_ORIGINS = [
    "https://joyvil.com",
    "https://www.joyvil.com",
    "https://back.joyvil.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# ✅ Allowed HTTP methods for cross-origin requests
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# ✅ Allowed headers in cross-origin requests
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# ✅ Allow credentials (cookies, authentication headers)
CORS_ALLOW_CREDENTIALS = True

# ✅ Set trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    "https://joyvil.com",
    "https://www.joyvil.com",
    "https://back.joyvil.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_EXPOSE_HEADERS = ['Set-Cookie']

# Application definition
INSTALLED_APPS = [
    'emailauth.apps.EmailAuthConfig',
    'joyfulset.apps.JoyfulsetConfig',
    'program.apps.ProgramConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'joyfulback.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'joyfulback.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': env('POSTGRES_DB'),
#         'USER': env('POSTGRES_USER'),
#         'PASSWORD': env('POSTGRES_PW'), 
#         'HOST': env('POSTGRES_HOST'), 
#         'PORT': env('POSTGRES_PORT'),
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "joyful-village",
        "USER": "joyful",
        "PASSWORD": "joyful",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Static & Media Files (Common Settings)
STATIC_URL = "/static/"
MEDIA_URL = "/media/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom Setting
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.naver.com'  # Naver's SMTP server
EMAIL_PORT = 587  # Naver uses port 587 for TLS
EMAIL_USE_TLS = True  # Enable TLS encryption
EMAIL_HOST_USER = 'yujin_career@naver.com'  # Your Naver email address
EMAIL_HOST_PASSWORD = 'saebyeok0225!'  # Your Naver email password

